### PR TITLE
Twilio SMS server setup

### PR DESCRIPTION
**Pull request by Aaron-Mendez2001**
## Description ##

This pull request is for adding the twilio API to the server, and setting up the routes so that SMS messages can be sent.

## Type ##

- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Review by Caleno83 — DISMISSED** [review]
Looks pretty good Aaron!!  I see that there are errors for test coverage, but I don't know why its showing that, but everything else looks fine.

**Comment by qweliant** [comment]
Make sure all test are passing before merging

**Review by Caleno83 — DISMISSED** [review]
Now that all tests are passing everything is better! as always good job!!

**Review by seth-nelson — DISMISSED** [review]
Nicely done Aaron! The code structure is clean, effective and easy to read. I haven't looked too much into the Twilio, but it looks great.

**Review by Caleno83 — APPROVED** [review]
Good, it should work now. Nice job!

**Review by qweliant — APPROVED** [review]
If you have to implement the same thing in customers, I think it best to create an interface for Twilio that can be dropped in anywhere. This is fine for now though

**Pull request merged**
